apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
      version: green
  template:
    metadata:
      labels:
        app: node-app
        version: green
    spec:
      containers:
      - name: node-app
        image: your-node-app-image:green
        ports:
        - containerPort: 8300
