apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
spec:
  ports:
  - name: http
    port: 8300
    targetPort: 8300
  - name: agent
    port: 8300
    targetPort: 8300
  selector:
    app: jenkins
  type: LoadBalancer

