name: Validate YAML files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  yamllint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install yamllint
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint

      - name: Run yamllint
        run: |
          yamllint . || true
          if [ $? -ne 0 ]; then
            echo "YAML Linting errors found:"
            yamllint . -f parsable
            exit 1
          fi
